#!/bin/bash

# Input params
if [ $# -ge 1 ]; then
  acqusetup=$1
fi
if [ $# -ge 2 ]; then
  outdir=$2
fi

#_______________________________________________________________________
runCalib()
{
  if [ -a $outdir/step$2_correction$1 ]; then
    echo "Directory $outdir/step$2_correction$1 already exists"
    rm -rf $outdir/step$2_correction$1/*
  else
    echo "Creating directory $outdir/step$2_correction$1..."
    mkdir $outdir/step$2_correction$1
  fi
  out=$outdir/step$2_correction$1
#  Worker $acqusetup
  AcquRoot --batch $acqusetup
  hadd -f nsummed.root $acquout/ARHist*.root
  root -l -b -q root/macros/AutoCalibMwpc.C"($1)" # creates a new mwpc_params.dat
  mv $acquout/ARHist*.root $out/
  mv nsummed.root $out/
#  mv Thread* $out/
}

#_______________________________________________________________________
# Find MWPC config file
analysis_setup=`cat ./data/$acqusetup | grep "^AnalysisSetup:" | awk '{print $2}'`
cb_setup=`cat ./data/${analysis_setup} | grep "^Apparatus:" | grep "TA2CentralApparatus" | awk '{print $4}'`
mwpc_setup=`cat ./data/${cb_setup} | grep "^Detector:" | grep "TA2CylMwpc" | awk '{print $4}'`
acquout=`cat ./data/$acqusetup | grep "^Directory:" | awk '{print $2}'`

#_______________________________________________________________________
# Run calibs
list_calibs="0 0 1 1 1 3 4 5"
step=0
for i in ${list_calibs}
do
  cat ./data/${mwpc_setup} | grep "^Intersection:" | sed 's/Intersection:[ \t]*//' > mwpc_params.dat # prepare mwpc_params.dat for AutoCalibMwpc.C
  let 'step +=1'
  runCalib $i $step
  sed -i 's/^Intersection:/# Intersection:/g' ./data/${mwpc_setup} # comment old Intersect:
  sed -i '/^#END/d' ./data/${mwpc_setup} # delete END
  echo "# After AutoCalibMwpc.C($i)" >> ./data/${mwpc_setup}
  while read line # Adding corrections
  do
    echo "Intersection: $line" >> ./data/${mwpc_setup}
  done < mwpc_params.dat
  echo >> ./data/${mwpc_setup}
  echo "#END" >> ./data/${mwpc_setup}
done

#_______________________________________________________________________
# Calibrated result
if [ -a $outdir/calibrated ]; then
  echo "Directory $outdir/calibrated already exists"
  rm -rf $outdir/calibrated/*
else
  echo "Creating directory out/$outdir/calibrated..."
  mkdir $outdir/calibrated
fi
out=$outdir/calibrated
#Worker $acqusetup
AcquRoot --batch $acqusetup
mv ./ARHist*.root $out/
cd $out
hadd -f nsummed.root ARHist*.root